In [6]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [7]:
df = pd.read_csv('./data.csv')

In [8]:
df.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [9]:

engine = create_engine(
    "postgresql://postgres:Kaushik%4013@localhost:5432/mlops_db"
)

df.to_sql(
    name="my_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data inserted successfully")

Data inserted successfully

In [10]:

# PostgreSQL credentials
DB_USER = "postgres"
DB_PASSWORD = "Kaushik%4013"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "mlops_db"

# Table name
TABLE_NAME = "my_table"

# Create PostgreSQL connection
DATABASE_URL = (
    f"postgresql://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

engine = create_engine(DATABASE_URL)

# Read CSV file
df = pd.read_csv("data.csv")

# Upload dataframe to PostgreSQL
df.to_sql(
    name=TABLE_NAME,
    con=engine,
    if_exists="replace",   # replace / append
    index=False
)

print("Data uploaded successfully")

# Load data from PostgreSQL
loaded_df = pd.read_sql(
    f"SELECT * FROM {TABLE_NAME}",
    engine
)

loaded_df.head()

Data uploaded successfully

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0